sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "10"
install:
    - npm install -g codecov
    - npm install
script:
  - codecov


after_success:
  - bash <(curl -s https://codecov.io/bash)
