sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "10"
install:
    # - npm i --save-dev istanbul@v1.1.0-alpha.1
    # - npm install -g codecov
    - npm install
script:
  # - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
  # - codecov
